<?php

########################################################################
# Extension Manager/Repository config file for ext: "flux_tutorial"
#
# Auto generated by Extension Builder 2012-12-06
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Flux Tutorial',
    'description' => "This extension should show the result of the Flux-Tutorial from: http://fedext.net/examples/flux/flexform-tutorial.html. Tested with Flux(4.7.13) and Typo3 (4.7.7)",
    'category' => 'example',
    'author' => 'Heiko Hardt',
    'author_email' => 'heiko.hardt@pixelpark.com',
    'author_company' => '',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'experimental',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '4.7.13',
    'constraints' => array(
        'depends' => array(
            'extbase' => '1.5',
            'fluid' => '1.5',
            'typo3' => '4.7',
            'flux'  => '',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>